services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./apps/auth-service/.env
      - ./apps/user-service/.env
    volumes:
      - postgres:/data/db
  api-gateway: 
    build:
      context: ./apps/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
    env_file:
      - ./apps/api-gateway/.env
    networks:
      - internal-networks
    restart: always
  
  auth-service:
    build: 
      context: ./apps/auth-service
    expose:
      - "3001"
    env_file:
      - ./apps/auth-service/.env
    networks:
      - internal-networks
    restart: always
  
  user-service: 
    build:
      context: ./apps/user-service
    expose:
      - "3002"
    env_file:
      - ./apps/user-service/.env
    restart: always
    networks:
      - internal-networks    
  
networks:
  internal-networks:
    driver: bridge
volumes:
  postgres: